public class addExample {
    public static Integer AddNumbers(Integer num1, Integer num2) {
        Integer result = num1 + num2;

        return result;
    }

    //Write a method to multiply two numbers and return the result

    public static Integer MultipleNumbers(Integer num1, Integer num2){
        Integer multipliedResult = num1 * num2;

        return multipliedResult;
    }

    //Write a method which will divide two numbers and give us the division result
    public static decimal divideNumbers(decimal num1, decimal num2){
        decimal divisionResult = num1 / num2;

        return divisionResult;
    }


    //write a method to subtract twoi numbers and return the result

    public static decimal subtractNumbers(decimal num1, decimal num2){
        decimal subResult = num1 - num2;

        return subResult;
    }

}